### ISSUE TITLE
Unexpected overwriting index.html

### ISSUE THREAD

**Issue by dmgolembiowski** [bocarw121/tailwind-yew-cli#1]
Instead of directly overwriting the `/index.html` in a preexisting path, is it possible to either merge the new `<link />` tag in place, or prompt the user for the accepted full-overwrite? 

I'm bringing this up because the CLI just nerfed my uncommitted changes on `index.html` and fear this might happen to others, too.

**Comment by bocarw121** [comment]
Hey David, sorry it wiped your uncommitted changes. Thanks for your input, I will look into it and get that resolved asap.
