### ISSUE TITLE
Creates a 40MB tailwindcss file with no extension. What is it?

### ISSUE THREAD

**Issue by konyogony** [bocarw121/tailwind-yew-cli#3]
![image](https://github.com/user-attachments/assets/592acf7b-16a2-43ef-898e-e2541e25b158)
I have just executed the commands and found this file with no extension which weights 40 MiB, any explanation to it?
![image](https://github.com/user-attachments/assets/f9ceb59f-9623-41ad-b16e-d7deb7e1049a)

**Comment by konyogony** [comment]
This might just be my unprofessionalism, but just wanted to make sure

**Comment by bocarw121** [comment]
Hi @kony-ogony, This is the Tailwind CLI build executable file that you will use to run the commands. If you look at the tailwind_info.md file you will get all of the information you need to run the file. Based on the size I see that you are using the Linux build. 

You can find the builds [here](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.9).

Let me know if you have anymore questions.

**Comment by konyogony** [comment]
Oh, Im sorry, totally my fault. I understand now, thanks for letting me know.

**Comment by bocarw121** [comment]
It's no problem at all, it's good to ask questions. You're welcome
